#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh,aliases,sesh,yazi"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES zsh  $DOTFILES/install


ln -fs ~/personal/dracula/themes/zsh/dracula-pro.zsh-theme ~/.oh-my-zsh/themes/dracula-pro.zsh-theme
ln -fs ~/personal/dracula/themes/vim/colors ~/.config/nvim/colors
ln -fs ~/personal/dracula/themes/vim/autoload ~/.config/nvim/autoload

