[default_session]
script_path = "~/.config/sesh/scripts/default.sh"

[[session]]
name = "Config 🛠"
path = "~/.dotfiles"
script_path = "~/.config/sesh/scripts/dotfiles.sh"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"
